### PR TITLE
Add --ios and --android options

### PR DESCRIPTION
**Pull request by dorianmariecom**

### CODE REVIEW

**Comment by anurag060** [comment]
Hi @dorianmariefr,
I have installed the package using `npm install -g kyle-ssg/react-native-app-id#pull/11/head` so that I get the latest code from your PR. But when I do `react-native-app-id com.myawesome.app "My Awsome App"`, it is throwing the below error
`const newID = process.argv[2]
                          ^
ReferenceError: Cannot access 'process' before initialization`

Am I missing something? Please help. 
Thank you.

**Comment by anurag060** [comment]
v16.14.2

**Comment by dorianmariefr** [comment]
Maybe try v18.1.0?

**Comment by dorianmariefr** [comment]
Or maybe try `import process from 'node:process';` at the top

**Pull request closed without merging**
